In [1]:
import xgboost as xgb
print(xgb.__version__)

3.4.1

In [9]:
from pathlib import Path
import pandas as pd

BASE_PATH = Path.cwd()
OUTPUT_PATH = BASE_PATH / "output"

FILE_HASIL = OUTPUT_PATH / "hasil_model_fixed_2025.xlsx"

print(FILE_HASIL)

d:\.STIS 64\SKRIPSI\Skripsi\PMT\output\hasil_model_fixed_2025.xlsx

In [10]:
df = pd.read_excel(FILE_HASIL)

print(df.shape)
display(df.head())

(280, 21)

,province,district,train,test,model,RMSE,IE20,EE20,IE40,EE40,...,EE60,Acc20,Acc40,Acc60,taudcl,tauGroup20,tauGroup40,tauGroup60,train_size,test_size
0,jogja,1,"[2022, 2023, 2024]",2025,Total_XGB,0.473794,0.486111,0.486111,0.298611,0.298611,...,0.201389,0.805556,0.761111,0.758333,0.545713,0.392361,0.502315,0.496528,2129,720
1,jogja,1,"[2022, 2023, 2024]",2025,XGB_Components,0.462585,0.479167,0.479167,0.295139,0.295139,...,0.203704,0.808333,0.763889,0.755556,0.547608,0.401042,0.508102,0.490741,2129,720
2,jogja,1,"[2022, 2023, 2024]",2025,RF_Components,0.462156,0.500000,0.500000,0.329861,0.329861,...,0.206019,0.800000,0.736111,0.752778,0.521935,0.375000,0.450231,0.484954,2129,720
3,jogja,1,"[2022, 2023, 2024]",2025,MultiOutputRegressor_XGB,0.462585,0.479167,0.479167,0.295139,0.295139,...,0.203704,0.808333,0.763889,0.755556,0.547608,0.401042,0.508102,0.490741,2129,720
4,jogja,1,"[2022, 2023, 2024]",2025,MultiOutputRegressor_RF,0.462156,0.500000,0.500000,0.329861,0.329861,...,0.206019,0.800000,0.736111,0.752778,0.521935,0.375000,0.450231,0.484954,2129,720

In [11]:
models_utama = [
    "Total_XGB",
    "XGB_Components",
    "MultiOutputTree_XGB",
    "RF_Components",
    "Multivariate_RF"
]

df_rmse = df[
    df["model"].isin(models_utama)
].copy()

display(df_rmse.head())

,province,district,train,test,model,RMSE,IE20,EE20,IE40,EE40,...,EE60,Acc20,Acc40,Acc60,taudcl,tauGroup20,tauGroup40,tauGroup60,train_size,test_size
0,jogja,1,"[2022, 2023, 2024]",2025,Total_XGB,0.473794,0.486111,0.486111,0.298611,0.298611,...,0.201389,0.805556,0.761111,0.758333,0.545713,0.392361,0.502315,0.496528,2129,720
1,jogja,1,"[2022, 2023, 2024]",2025,XGB_Components,0.462585,0.479167,0.479167,0.295139,0.295139,...,0.203704,0.808333,0.763889,0.755556,0.547608,0.401042,0.508102,0.490741,2129,720
2,jogja,1,"[2022, 2023, 2024]",2025,RF_Components,0.462156,0.500000,0.500000,0.329861,0.329861,...,0.206019,0.800000,0.736111,0.752778,0.521935,0.375000,0.450231,0.484954,2129,720
5,jogja,1,"[2022, 2023, 2024]",2025,MultiOutputTree_XGB,0.463705,0.493056,0.493056,0.295139,0.295139,...,0.201389,0.802778,0.763889,0.758333,0.546858,0.383681,0.508102,0.496528,2129,720
6,jogja,1,"[2022, 2023, 2024]",2025,Multivariate_RF,0.464974,0.506944,0.506944,0.326389,0.326389,...,0.210648,0.797222,0.738889,0.747222,0.519779,0.366319,0.456019,0.473380,2129,720

In [12]:
tabel_rmse = (
    df_rmse
    .pivot_table(
        index=["province", "district"],
        columns="model",
        values="RMSE"
    )
    .reset_index()
)

# Urutkan kolom sesuai kebutuhan
tabel_rmse = tabel_rmse[
    [
        "province",
        "district",
        "Total_XGB",
        "XGB_Components",
        "MultiOutputTree_XGB",
        "RF_Components",
        "Multivariate_RF"
    ]
]

# Nama kolom lebih enak untuk tabel skripsi
tabel_rmse = tabel_rmse.rename(columns={
    "province": "Provinsi",
    "district": "Kabupaten/Kota",
    "Total_XGB": "Total XGB",
    "XGB_Components": "XGB Components",
    "MultiOutputTree_XGB": "Multi-output Tree XGB",
    "RF_Components": "RF Components",
    "Multivariate_RF": "Multivariate RF"
})

display(
    tabel_rmse.round(4)
)

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,jateng,1,0.4677,0.4636,0.4641,0.4918,0.4984
1,jateng,2,0.4249,0.4186,0.4190,0.4522,0.4593
2,jateng,3,0.4151,0.4134,0.4138,0.4367,0.4405
3,jateng,4,0.4670,0.4596,0.4591,0.4928,0.4967
4,jateng,5,0.4475,0.4450,0.4417,0.4684,0.4691
5,jateng,6,0.3784,0.3734,0.3713,0.3987,0.4036
6,jateng,7,0.4610,0.4590,0.4585,0.4826,0.4860
7,jateng,8,0.4517,0.4513,0.4514,0.4860,0.4892
8,jateng,9,0.4530,0.4461,0.4477,0.4740,0.4751
9,jateng,10,0.4301,0.4272,0.4269,0.4482,0.4552
10,jateng,11,0.4601,0.4512,0.4512,0.4790,0.4824
11,jateng,12,0.4631,0.4557,0.4537,0.4597,0.4632
12,jateng,13,0.3900,0.3890,0.3906,0.4231,0.4249
13,jateng,14,0.4786,0.4728,0.4742,0.4999,0.5032
14,jateng,15,0.4124,0.4059,0.4079,0.4397,0.4467
15,jateng,16,0.4883,0.4760,0.4761,0.4932,0.4962
16,jateng,17,0.5138,0.4980,0.4966,0.4853,0.4850
17,jateng,18,0.4503,0.4401,0.4390,0.4475,0.4518
18,jateng,19,0.4265,0.4202,0.4212,0.4440,0.4499
19,jateng,20,0.4112,0.4044,0.4042,0.4305,0.4367
20,jateng,21,0.4560,0.4453,0.4425,0.4446,0.4487
21,jateng,22,0.4558,0.4574,0.4573,0.4934,0.4981
22,jateng,23,0.4468,0.4412,0.4445,0.4604,0.4660
23,jateng,24,0.4383,0.4359,0.4379,0.4566,0.4714
24,jateng,25,0.4139,0.4153,0.4146,0.4454,0.4488
25,jateng,26,0.4043,0.3996,0.3985,0.4209,0.4242
26,jateng,27,0.4589,0.4569,0.4571,0.4884,0.4936
27,jateng,28,0.4290,0.4233,0.4205,0.4410,0.4448
28,jateng,29,0.4266,0.4203,0.4203,0.4573,0.4665
29,jateng,71,0.5022,0.4830,0.4813,0.4995,0.4941
30,jateng,72,0.4489,0.4431,0.4393,0.4489,0.4513
31,jateng,73,0.4850,0.4744,0.4745,0.4965,0.5017
32,jateng,74,0.4697,0.4608,0.4606,0.4915,0.4989
33,jateng,75,0.4158,0.4082,0.4033,0.4134,0.4154
34,jateng,76,0.4149,0.4049,0.4018,0.4313,0.4317
35,jogja,1,0.4738,0.4626,0.4637,0.4622,0.4650
36,jogja,2,0.4753,0.4645,0.4642,0.4903,0.4951
37,jogja,3,0.4377,0.4411,0.4425,0.4701,0.4728
38,jogja,4,0.3975,0.3903,0.3914,0.4213,0.4262
39,jogja,71,0.4842,0.4754,0.4772,0.4999,0.5083

In [13]:
provinsi_label = {
    "jogja": "D.I. Yogyakarta",
    "jateng": "Jawa Tengah"
}

tabel_rmse["Provinsi"] = (
    tabel_rmse["Provinsi"]
    .map(provinsi_label)
)

display(
    tabel_rmse.round(4)
)

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,Jawa Tengah,1,0.4677,0.4636,0.4641,0.4918,0.4984
1,Jawa Tengah,2,0.4249,0.4186,0.4190,0.4522,0.4593
2,Jawa Tengah,3,0.4151,0.4134,0.4138,0.4367,0.4405
3,Jawa Tengah,4,0.4670,0.4596,0.4591,0.4928,0.4967
4,Jawa Tengah,5,0.4475,0.4450,0.4417,0.4684,0.4691
5,Jawa Tengah,6,0.3784,0.3734,0.3713,0.3987,0.4036
6,Jawa Tengah,7,0.4610,0.4590,0.4585,0.4826,0.4860
7,Jawa Tengah,8,0.4517,0.4513,0.4514,0.4860,0.4892
8,Jawa Tengah,9,0.4530,0.4461,0.4477,0.4740,0.4751
9,Jawa Tengah,10,0.4301,0.4272,0.4269,0.4482,0.4552
10,Jawa Tengah,11,0.4601,0.4512,0.4512,0.4790,0.4824
11,Jawa Tengah,12,0.4631,0.4557,0.4537,0.4597,0.4632
12,Jawa Tengah,13,0.3900,0.3890,0.3906,0.4231,0.4249
13,Jawa Tengah,14,0.4786,0.4728,0.4742,0.4999,0.5032
14,Jawa Tengah,15,0.4124,0.4059,0.4079,0.4397,0.4467
15,Jawa Tengah,16,0.4883,0.4760,0.4761,0.4932,0.4962
16,Jawa Tengah,17,0.5138,0.4980,0.4966,0.4853,0.4850
17,Jawa Tengah,18,0.4503,0.4401,0.4390,0.4475,0.4518
18,Jawa Tengah,19,0.4265,0.4202,0.4212,0.4440,0.4499
19,Jawa Tengah,20,0.4112,0.4044,0.4042,0.4305,0.4367
20,Jawa Tengah,21,0.4560,0.4453,0.4425,0.4446,0.4487
21,Jawa Tengah,22,0.4558,0.4574,0.4573,0.4934,0.4981
22,Jawa Tengah,23,0.4468,0.4412,0.4445,0.4604,0.4660
23,Jawa Tengah,24,0.4383,0.4359,0.4379,0.4566,0.4714
24,Jawa Tengah,25,0.4139,0.4153,0.4146,0.4454,0.4488
25,Jawa Tengah,26,0.4043,0.3996,0.3985,0.4209,0.4242
26,Jawa Tengah,27,0.4589,0.4569,0.4571,0.4884,0.4936
27,Jawa Tengah,28,0.4290,0.4233,0.4205,0.4410,0.4448
28,Jawa Tengah,29,0.4266,0.4203,0.4203,0.4573,0.4665
29,Jawa Tengah,71,0.5022,0.4830,0.4813,0.4995,0.4941
30,Jawa Tengah,72,0.4489,0.4431,0.4393,0.4489,0.4513
31,Jawa Tengah,73,0.4850,0.4744,0.4745,0.4965,0.5017
32,Jawa Tengah,74,0.4697,0.4608,0.4606,0.4915,0.4989
33,Jawa Tengah,75,0.4158,0.4082,0.4033,0.4134,0.4154
34,Jawa Tengah,76,0.4149,0.4049,0.4018,0.4313,0.4317
35,D.I. Yogyakarta,1,0.4738,0.4626,0.4637,0.4622,0.4650
36,D.I. Yogyakarta,2,0.4753,0.4645,0.4642,0.4903,0.4951
37,D.I. Yogyakarta,3,0.4377,0.4411,0.4425,0.4701,0.4728
38,D.I. Yogyakarta,4,0.3975,0.3903,0.3914,0.4213,0.4262
39,D.I. Yogyakarta,71,0.4842,0.4754,0.4772,0.4999,0.5083

In [14]:
kolom_model = [
    "Total XGB",
    "XGB Components",
    "Multi-output Tree XGB",
    "RF Components",
    "Multivariate RF"
]

tabel_rmse["Model RMSE Terendah"] = (
    tabel_rmse[kolom_model]
    .idxmin(axis=1)
)

tabel_rmse["RMSE Terendah"] = (
    tabel_rmse[kolom_model]
    .min(axis=1)
)

display(
    tabel_rmse.round(4)
)

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF,Model RMSE Terendah,RMSE Terendah
0,Jawa Tengah,1,0.4677,0.4636,0.4641,0.4918,0.4984,XGB Components,0.4636
1,Jawa Tengah,2,0.4249,0.4186,0.4190,0.4522,0.4593,XGB Components,0.4186
2,Jawa Tengah,3,0.4151,0.4134,0.4138,0.4367,0.4405,XGB Components,0.4134
3,Jawa Tengah,4,0.4670,0.4596,0.4591,0.4928,0.4967,Multi-output Tree XGB,0.4591
4,Jawa Tengah,5,0.4475,0.4450,0.4417,0.4684,0.4691,Multi-output Tree XGB,0.4417
5,Jawa Tengah,6,0.3784,0.3734,0.3713,0.3987,0.4036,Multi-output Tree XGB,0.3713
6,Jawa Tengah,7,0.4610,0.4590,0.4585,0.4826,0.4860,Multi-output Tree XGB,0.4585
7,Jawa Tengah,8,0.4517,0.4513,0.4514,0.4860,0.4892,XGB Components,0.4513
8,Jawa Tengah,9,0.4530,0.4461,0.4477,0.4740,0.4751,XGB Components,0.4461
9,Jawa Tengah,10,0.4301,0.4272,0.4269,0.4482,0.4552,Multi-output Tree XGB,0.4269
10,Jawa Tengah,11,0.4601,0.4512,0.4512,0.4790,0.4824,XGB Components,0.4512
11,Jawa Tengah,12,0.4631,0.4557,0.4537,0.4597,0.4632,Multi-output Tree XGB,0.4537
12,Jawa Tengah,13,0.3900,0.3890,0.3906,0.4231,0.4249,XGB Components,0.3890
13,Jawa Tengah,14,0.4786,0.4728,0.4742,0.4999,0.5032,XGB Components,0.4728
14,Jawa Tengah,15,0.4124,0.4059,0.4079,0.4397,0.4467,XGB Components,0.4059
15,Jawa Tengah,16,0.4883,0.4760,0.4761,0.4932,0.4962,XGB Components,0.4760
16,Jawa Tengah,17,0.5138,0.4980,0.4966,0.4853,0.4850,Multivariate RF,0.4850
17,Jawa Tengah,18,0.4503,0.4401,0.4390,0.4475,0.4518,Multi-output Tree XGB,0.4390
18,Jawa Tengah,19,0.4265,0.4202,0.4212,0.4440,0.4499,XGB Components,0.4202
19,Jawa Tengah,20,0.4112,0.4044,0.4042,0.4305,0.4367,Multi-output Tree XGB,0.4042
20,Jawa Tengah,21,0.4560,0.4453,0.4425,0.4446,0.4487,Multi-output Tree XGB,0.4425
21,Jawa Tengah,22,0.4558,0.4574,0.4573,0.4934,0.4981,Total XGB,0.4558
22,Jawa Tengah,23,0.4468,0.4412,0.4445,0.4604,0.4660,XGB Components,0.4412
23,Jawa Tengah,24,0.4383,0.4359,0.4379,0.4566,0.4714,XGB Components,0.4359
24,Jawa Tengah,25,0.4139,0.4153,0.4146,0.4454,0.4488,Total XGB,0.4139
25,Jawa Tengah,26,0.4043,0.3996,0.3985,0.4209,0.4242,Multi-output Tree XGB,0.3985
26,Jawa Tengah,27,0.4589,0.4569,0.4571,0.4884,0.4936,XGB Components,0.4569
27,Jawa Tengah,28,0.4290,0.4233,0.4205,0.4410,0.4448,Multi-output Tree XGB,0.4205
28,Jawa Tengah,29,0.4266,0.4203,0.4203,0.4573,0.4665,Multi-output Tree XGB,0.4203
29,Jawa Tengah,71,0.5022,0.4830,0.4813,0.4995,0.4941,Multi-output Tree XGB,0.4813
30,Jawa Tengah,72,0.4489,0.4431,0.4393,0.4489,0.4513,Multi-output Tree XGB,0.4393
31,Jawa Tengah,73,0.4850,0.4744,0.4745,0.4965,0.5017,XGB Components,0.4744
32,Jawa Tengah,74,0.4697,0.4608,0.4606,0.4915,0.4989,Multi-output Tree XGB,0.4606
33,Jawa Tengah,75,0.4158,0.4082,0.4033,0.4134,0.4154,Multi-output Tree XGB,0.4033
34,Jawa Tengah,76,0.4149,0.4049,0.4018,0.4313,0.4317,Multi-output Tree XGB,0.4018
35,D.I. Yogyakarta,1,0.4738,0.4626,0.4637,0.4622,0.4650,RF Components,0.4622
36,D.I. Yogyakarta,2,0.4753,0.4645,0.4642,0.4903,0.4951,Multi-output Tree XGB,0.4642
37,D.I. Yogyakarta,3,0.4377,0.4411,0.4425,0.4701,0.4728,Total XGB,0.4377
38,D.I. Yogyakarta,4,0.3975,0.3903,0.3914,0.4213,0.4262,XGB Components,0.3903
39,D.I. Yogyakarta,71,0.4842,0.4754,0.4772,0.4999,0.5083,XGB Components,0.4754

In [15]:
ringkasan_rmse = (
    tabel_rmse
    .groupby("Provinsi")[kolom_model]
    .mean()
    .reset_index()
)

display(
    ringkasan_rmse.round(4)
)

model,Provinsi,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,D.I. Yogyakarta,0.4537,0.4468,0.4478,0.4687,0.4735
1,Jawa Tengah,0.4445,0.4383,0.4378,0.4606,0.4648

In [16]:
file_output = OUTPUT_PATH / "tabel_RMSE_5_model_2025.xlsx"

with pd.ExcelWriter(
    file_output,
    engine="openpyxl"
) as writer:

    tabel_rmse.round(4).to_excel(
        writer,
        sheet_name="RMSE_per_kabupaten",
        index=False
    )

    ringkasan_rmse.round(4).to_excel(
        writer,
        sheet_name="Rata_rata_provinsi",
        index=False
    )

print("Tersimpan:", file_output)

Tersimpan: d:\.STIS 64\SKRIPSI\Skripsi\PMT\output\tabel_RMSE_5_model_2025.xlsx

In [17]:
models_utama = [
    "Total_XGB",
    "XGB_Components",
    "MultiOutputTree_XGB",
    "RF_Components",
    "Multivariate_RF"
]

df_tau = df[
    df["model"].isin(models_utama)
].copy()

tabel_tau = (
    df_tau
    .pivot_table(
        index=["province", "district"],
        columns="model",
        values="taudcl"
    )
    .reset_index()
)

tabel_tau = tabel_tau[
    [
        "province",
        "district",
        "Total_XGB",
        "XGB_Components",
        "MultiOutputTree_XGB",
        "RF_Components",
        "Multivariate_RF"
    ]
]

tabel_tau = tabel_tau.rename(columns={
    "province": "Provinsi",
    "district": "Kabupaten/Kota",
    "Total_XGB": "Total XGB",
    "XGB_Components": "XGB Components",
    "MultiOutputTree_XGB": "Multi-output Tree XGB",
    "RF_Components": "RF Components",
    "Multivariate_RF": "Multivariate RF"
})

provinsi_label = {
    "jogja": "D.I. Yogyakarta",
    "jateng": "Jawa Tengah"
}

tabel_tau["Provinsi"] = (
    tabel_tau["Provinsi"]
    .map(provinsi_label)
)

display(tabel_tau.round(4))

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,Jawa Tengah,1,0.5303,0.5280,0.5292,0.4962,0.4879
1,Jawa Tengah,2,0.5783,0.5800,0.5768,0.5234,0.5147
2,Jawa Tengah,3,0.5214,0.5237,0.5199,0.4826,0.4762
3,Jawa Tengah,4,0.5822,0.5886,0.5806,0.5216,0.5088
4,Jawa Tengah,5,0.5215,0.5157,0.5216,0.5053,0.5000
5,Jawa Tengah,6,0.5305,0.5264,0.5304,0.4703,0.4597
6,Jawa Tengah,7,0.5054,0.5072,0.5134,0.4806,0.4732
7,Jawa Tengah,8,0.5416,0.5484,0.5440,0.4971,0.4902
8,Jawa Tengah,9,0.5237,0.5218,0.5180,0.4810,0.4746
9,Jawa Tengah,10,0.5223,0.5234,0.5245,0.4959,0.4868
10,Jawa Tengah,11,0.5972,0.5994,0.5931,0.5552,0.5517
11,Jawa Tengah,12,0.4906,0.4921,0.4956,0.4722,0.4555
12,Jawa Tengah,13,0.5773,0.5813,0.5707,0.5316,0.5319
13,Jawa Tengah,14,0.5124,0.5137,0.5125,0.4779,0.4747
14,Jawa Tengah,15,0.4859,0.4905,0.4838,0.4444,0.4289
15,Jawa Tengah,16,0.5284,0.5330,0.5293,0.4813,0.4689
16,Jawa Tengah,17,0.4741,0.4818,0.4835,0.4433,0.4344
17,Jawa Tengah,18,0.4981,0.5076,0.5059,0.4797,0.4752
18,Jawa Tengah,19,0.5103,0.5128,0.5096,0.4715,0.4584
19,Jawa Tengah,20,0.4996,0.4981,0.4959,0.4562,0.4422
20,Jawa Tengah,21,0.5023,0.5003,0.5048,0.4630,0.4560
21,Jawa Tengah,22,0.5356,0.5341,0.5356,0.4967,0.4807
22,Jawa Tengah,23,0.5373,0.5383,0.5368,0.5153,0.5074
23,Jawa Tengah,24,0.5156,0.5184,0.5198,0.4865,0.4604
24,Jawa Tengah,25,0.5262,0.5283,0.5231,0.4922,0.4873
25,Jawa Tengah,26,0.5493,0.5442,0.5488,0.5052,0.4983
26,Jawa Tengah,27,0.4981,0.4989,0.5005,0.4655,0.4534
27,Jawa Tengah,28,0.5283,0.5244,0.5258,0.4902,0.4917
28,Jawa Tengah,29,0.5004,0.5044,0.5024,0.4260,0.4127
29,Jawa Tengah,71,0.6334,0.6351,0.6358,0.5811,0.5764
30,Jawa Tengah,72,0.6108,0.6129,0.6089,0.6014,0.5941
31,Jawa Tengah,73,0.6138,0.6136,0.6119,0.5779,0.5796
32,Jawa Tengah,74,0.6383,0.6371,0.6376,0.5819,0.5759
33,Jawa Tengah,75,0.5357,0.5335,0.5313,0.5231,0.5184
34,Jawa Tengah,76,0.5740,0.5748,0.5802,0.5379,0.5265
35,D.I. Yogyakarta,1,0.5457,0.5476,0.5469,0.5219,0.5198
36,D.I. Yogyakarta,2,0.6200,0.6270,0.6226,0.5948,0.5809
37,D.I. Yogyakarta,3,0.4885,0.4890,0.4884,0.4587,0.4433
38,D.I. Yogyakarta,4,0.6758,0.6749,0.6736,0.6359,0.6297
39,D.I. Yogyakarta,71,0.6445,0.6507,0.6433,0.6066,0.5982

In [18]:
kolom_model = [
    "Total XGB",
    "XGB Components",
    "Multi-output Tree XGB",
    "RF Components",
    "Multivariate RF"
]

tabel_tau["Model Tau-b Tertinggi"] = (
    tabel_tau[kolom_model]
    .idxmax(axis=1)
)

tabel_tau["Tau-b Tertinggi"] = (
    tabel_tau[kolom_model]
    .max(axis=1)
)

display(tabel_tau.round(4))

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF,Model Tau-b Tertinggi,Tau-b Tertinggi
0,Jawa Tengah,1,0.5303,0.5280,0.5292,0.4962,0.4879,Total XGB,0.5303
1,Jawa Tengah,2,0.5783,0.5800,0.5768,0.5234,0.5147,XGB Components,0.5800
2,Jawa Tengah,3,0.5214,0.5237,0.5199,0.4826,0.4762,XGB Components,0.5237
3,Jawa Tengah,4,0.5822,0.5886,0.5806,0.5216,0.5088,XGB Components,0.5886
4,Jawa Tengah,5,0.5215,0.5157,0.5216,0.5053,0.5000,Multi-output Tree XGB,0.5216
5,Jawa Tengah,6,0.5305,0.5264,0.5304,0.4703,0.4597,Total XGB,0.5305
6,Jawa Tengah,7,0.5054,0.5072,0.5134,0.4806,0.4732,Multi-output Tree XGB,0.5134
7,Jawa Tengah,8,0.5416,0.5484,0.5440,0.4971,0.4902,XGB Components,0.5484
8,Jawa Tengah,9,0.5237,0.5218,0.5180,0.4810,0.4746,Total XGB,0.5237
9,Jawa Tengah,10,0.5223,0.5234,0.5245,0.4959,0.4868,Multi-output Tree XGB,0.5245
10,Jawa Tengah,11,0.5972,0.5994,0.5931,0.5552,0.5517,XGB Components,0.5994
11,Jawa Tengah,12,0.4906,0.4921,0.4956,0.4722,0.4555,Multi-output Tree XGB,0.4956
12,Jawa Tengah,13,0.5773,0.5813,0.5707,0.5316,0.5319,XGB Components,0.5813
13,Jawa Tengah,14,0.5124,0.5137,0.5125,0.4779,0.4747,XGB Components,0.5137
14,Jawa Tengah,15,0.4859,0.4905,0.4838,0.4444,0.4289,XGB Components,0.4905
15,Jawa Tengah,16,0.5284,0.5330,0.5293,0.4813,0.4689,XGB Components,0.5330
16,Jawa Tengah,17,0.4741,0.4818,0.4835,0.4433,0.4344,Multi-output Tree XGB,0.4835
17,Jawa Tengah,18,0.4981,0.5076,0.5059,0.4797,0.4752,XGB Components,0.5076
18,Jawa Tengah,19,0.5103,0.5128,0.5096,0.4715,0.4584,XGB Components,0.5128
19,Jawa Tengah,20,0.4996,0.4981,0.4959,0.4562,0.4422,Total XGB,0.4996
20,Jawa Tengah,21,0.5023,0.5003,0.5048,0.4630,0.4560,Multi-output Tree XGB,0.5048
21,Jawa Tengah,22,0.5356,0.5341,0.5356,0.4967,0.4807,Multi-output Tree XGB,0.5356
22,Jawa Tengah,23,0.5373,0.5383,0.5368,0.5153,0.5074,XGB Components,0.5383
23,Jawa Tengah,24,0.5156,0.5184,0.5198,0.4865,0.4604,Multi-output Tree XGB,0.5198
24,Jawa Tengah,25,0.5262,0.5283,0.5231,0.4922,0.4873,XGB Components,0.5283
25,Jawa Tengah,26,0.5493,0.5442,0.5488,0.5052,0.4983,Total XGB,0.5493
26,Jawa Tengah,27,0.4981,0.4989,0.5005,0.4655,0.4534,Multi-output Tree XGB,0.5005
27,Jawa Tengah,28,0.5283,0.5244,0.5258,0.4902,0.4917,Total XGB,0.5283
28,Jawa Tengah,29,0.5004,0.5044,0.5024,0.4260,0.4127,XGB Components,0.5044
29,Jawa Tengah,71,0.6334,0.6351,0.6358,0.5811,0.5764,Multi-output Tree XGB,0.6358
30,Jawa Tengah,72,0.6108,0.6129,0.6089,0.6014,0.5941,XGB Components,0.6129
31,Jawa Tengah,73,0.6138,0.6136,0.6119,0.5779,0.5796,Total XGB,0.6138
32,Jawa Tengah,74,0.6383,0.6371,0.6376,0.5819,0.5759,Total XGB,0.6383
33,Jawa Tengah,75,0.5357,0.5335,0.5313,0.5231,0.5184,Total XGB,0.5357
34,Jawa Tengah,76,0.5740,0.5748,0.5802,0.5379,0.5265,Multi-output Tree XGB,0.5802
35,D.I. Yogyakarta,1,0.5457,0.5476,0.5469,0.5219,0.5198,XGB Components,0.5476
36,D.I. Yogyakarta,2,0.6200,0.6270,0.6226,0.5948,0.5809,XGB Components,0.6270
37,D.I. Yogyakarta,3,0.4885,0.4890,0.4884,0.4587,0.4433,XGB Components,0.4890
38,D.I. Yogyakarta,4,0.6758,0.6749,0.6736,0.6359,0.6297,Total XGB,0.6758
39,D.I. Yogyakarta,71,0.6445,0.6507,0.6433,0.6066,0.5982,XGB Components,0.6507

In [19]:
ringkasan_tau = (
    tabel_tau
    .groupby("Provinsi")[kolom_model]
    .mean()
    .reset_index()
)

display(ringkasan_tau.round(4))

model,Provinsi,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,D.I. Yogyakarta,0.5949,0.5979,0.5950,0.5636,0.5544
1,Jawa Tengah,0.5380,0.5392,0.5383,0.5003,0.4918

In [20]:
file_tau = OUTPUT_PATH / "tabel_Kendall_Tau_5_model_2025.xlsx"

with pd.ExcelWriter(
    file_tau,
    engine="openpyxl"
) as writer:

    tabel_tau.round(4).to_excel(
        writer,
        sheet_name="Tau_per_kabupaten",
        index=False
    )

    ringkasan_tau.round(4).to_excel(
        writer,
        sheet_name="Rata_rata_provinsi",
        index=False
    )


print("Tersimpan:", file_tau)

Tersimpan: d:\.STIS 64\SKRIPSI\Skripsi\PMT\output\tabel_Kendall_Tau_5_model_2025.xlsx

In [27]:
df_ie40 = df[
    df["model"].isin(models_utama)
].copy()

tabel_ie40 = (
    df_ie40
    .pivot_table(
        index=["province", "district"],
        columns="model",
        values="IE40"
    )
    .reset_index()
)

tabel_ie40 = tabel_ie40[
    [
        "province",
        "district",
        "Total_XGB",
        "XGB_Components",
        "MultiOutputTree_XGB",
        "RF_Components",
        "Multivariate_RF"
    ]
]

tabel_ie40 = tabel_ie40.rename(columns={
    "province": "Provinsi",
    "district": "Kabupaten/Kota",
    "Total_XGB": "Total XGB",
    "XGB_Components": "XGB Components",
    "MultiOutputTree_XGB": "Multi-output Tree XGB",
    "RF_Components": "RF Components",
    "Multivariate_RF": "Multivariate RF"
})

tabel_ie40["Provinsi"] = (
    tabel_ie40["Provinsi"]
    .map(provinsi_label)
)

display(tabel_ie40.round(4))

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,Jawa Tengah,1,0.3333,0.3281,0.3333,0.3464,0.3542
1,Jawa Tengah,2,0.3073,0.3125,0.3125,0.3281,0.3255
2,Jawa Tengah,3,0.3601,0.3482,0.3542,0.3929,0.3958
3,Jawa Tengah,4,0.2711,0.2741,0.2711,0.3133,0.3283
4,Jawa Tengah,5,0.3210,0.3267,0.3210,0.3182,0.3239
5,Jawa Tengah,6,0.3165,0.3323,0.3196,0.3449,0.3671
6,Jawa Tengah,7,0.3426,0.3364,0.3395,0.3580,0.3549
7,Jawa Tengah,8,0.3153,0.3125,0.3068,0.3438,0.3466
8,Jawa Tengah,9,0.2971,0.2971,0.3029,0.3529,0.3471
9,Jawa Tengah,10,0.3427,0.3427,0.3371,0.3539,0.3483
10,Jawa Tengah,11,0.2560,0.2620,0.2590,0.2861,0.2952
11,Jawa Tengah,12,0.3218,0.3161,0.3075,0.3362,0.3534
12,Jawa Tengah,13,0.3079,0.3079,0.3140,0.3171,0.3201
13,Jawa Tengah,14,0.3223,0.3223,0.3253,0.3404,0.3464
14,Jawa Tengah,15,0.3522,0.3602,0.3575,0.3683,0.3763
15,Jawa Tengah,16,0.3171,0.3049,0.3079,0.3323,0.3598
16,Jawa Tengah,17,0.3636,0.3474,0.3474,0.3701,0.3669
17,Jawa Tengah,18,0.3242,0.3104,0.3187,0.3324,0.3324
18,Jawa Tengah,19,0.3179,0.3179,0.3210,0.3333,0.3426
19,Jawa Tengah,20,0.3276,0.3391,0.3276,0.3563,0.3649
20,Jawa Tengah,21,0.3218,0.3276,0.3247,0.3333,0.3391
21,Jawa Tengah,22,0.3227,0.3140,0.3140,0.3285,0.3314
22,Jawa Tengah,23,0.3031,0.3031,0.3000,0.3406,0.3188
23,Jawa Tengah,24,0.3214,0.3274,0.3155,0.3333,0.3661
24,Jawa Tengah,25,0.3201,0.3079,0.3262,0.3354,0.3415
25,Jawa Tengah,26,0.3079,0.3049,0.3049,0.3415,0.3354
26,Jawa Tengah,27,0.3361,0.3333,0.3250,0.3444,0.3444
27,Jawa Tengah,28,0.3043,0.3071,0.3043,0.3179,0.3261
28,Jawa Tengah,29,0.3258,0.3283,0.3258,0.3939,0.3737
29,Jawa Tengah,71,0.2685,0.2731,0.2731,0.3009,0.3009
30,Jawa Tengah,72,0.2800,0.2867,0.2833,0.2767,0.2767
31,Jawa Tengah,73,0.2869,0.2910,0.2787,0.2910,0.2951
32,Jawa Tengah,74,0.2392,0.2419,0.2446,0.2930,0.3038
33,Jawa Tengah,75,0.2962,0.2962,0.3038,0.3154,0.3192
34,Jawa Tengah,76,0.2969,0.2969,0.2891,0.3281,0.3281
35,D.I. Yogyakarta,1,0.2986,0.2951,0.2951,0.3299,0.3264
36,D.I. Yogyakarta,2,0.2708,0.2649,0.2649,0.2887,0.2946
37,D.I. Yogyakarta,3,0.3269,0.3333,0.3365,0.3429,0.3526
38,D.I. Yogyakarta,4,0.2360,0.2331,0.2331,0.2472,0.2500
39,D.I. Yogyakarta,71,0.2428,0.2355,0.2428,0.2464,0.2609

In [37]:
# ==========================================
# UBAH IE40 MENJADI PERSEN
# ==========================================

tabel_ie40_persen = tabel_ie40.copy()

# Ubah IE40 kelima model menjadi persen
for col in kolom_model:
    tabel_ie40_persen[col] = tabel_ie40_persen[col] * 100

display(tabel_ie40_persen.round(2))

model,Provinsi,Kabupaten/Kota,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,Jawa Tengah,1,33.33,32.81,33.33,34.64,35.42
1,Jawa Tengah,2,30.73,31.25,31.25,32.81,32.55
2,Jawa Tengah,3,36.01,34.82,35.42,39.29,39.58
3,Jawa Tengah,4,27.11,27.41,27.11,31.33,32.83
4,Jawa Tengah,5,32.10,32.67,32.10,31.82,32.39
5,Jawa Tengah,6,31.65,33.23,31.96,34.49,36.71
6,Jawa Tengah,7,34.26,33.64,33.95,35.80,35.49
7,Jawa Tengah,8,31.53,31.25,30.68,34.38,34.66
8,Jawa Tengah,9,29.71,29.71,30.29,35.29,34.71
9,Jawa Tengah,10,34.27,34.27,33.71,35.39,34.83
10,Jawa Tengah,11,25.60,26.20,25.90,28.61,29.52
11,Jawa Tengah,12,32.18,31.61,30.75,33.62,35.34
12,Jawa Tengah,13,30.79,30.79,31.40,31.71,32.01
13,Jawa Tengah,14,32.23,32.23,32.53,34.04,34.64
14,Jawa Tengah,15,35.22,36.02,35.75,36.83,37.63
15,Jawa Tengah,16,31.71,30.49,30.79,33.23,35.98
16,Jawa Tengah,17,36.36,34.74,34.74,37.01,36.69
17,Jawa Tengah,18,32.42,31.04,31.87,33.24,33.24
18,Jawa Tengah,19,31.79,31.79,32.10,33.33,34.26
19,Jawa Tengah,20,32.76,33.91,32.76,35.63,36.49
20,Jawa Tengah,21,32.18,32.76,32.47,33.33,33.91
21,Jawa Tengah,22,32.27,31.40,31.40,32.85,33.14
22,Jawa Tengah,23,30.31,30.31,30.00,34.06,31.87
23,Jawa Tengah,24,32.14,32.74,31.55,33.33,36.61
24,Jawa Tengah,25,32.01,30.79,32.62,33.54,34.15
25,Jawa Tengah,26,30.79,30.49,30.49,34.15,33.54
26,Jawa Tengah,27,33.61,33.33,32.50,34.44,34.44
27,Jawa Tengah,28,30.43,30.71,30.43,31.79,32.61
28,Jawa Tengah,29,32.58,32.83,32.58,39.39,37.37
29,Jawa Tengah,71,26.85,27.31,27.31,30.09,30.09
30,Jawa Tengah,72,28.00,28.67,28.33,27.67,27.67
31,Jawa Tengah,73,28.69,29.10,27.87,29.10,29.51
32,Jawa Tengah,74,23.92,24.19,24.46,29.30,30.38
33,Jawa Tengah,75,29.62,29.62,30.38,31.54,31.92
34,Jawa Tengah,76,29.69,29.69,28.91,32.81,32.81
35,D.I. Yogyakarta,1,29.86,29.51,29.51,32.99,32.64
36,D.I. Yogyakarta,2,27.08,26.49,26.49,28.87,29.46
37,D.I. Yogyakarta,3,32.69,33.33,33.65,34.29,35.26
38,D.I. Yogyakarta,4,23.60,23.31,23.31,24.72,25.00
39,D.I. Yogyakarta,71,24.28,23.55,24.28,24.64,26.09

In [41]:
ringkasan_ie40 = (
    tabel_ie40
    .groupby("Provinsi")[kolom_model]
    .mean()
    .reset_index()
)

display(ringkasan_ie40.round(4))

model,Provinsi,Total XGB,XGB Components,Multi-output Tree XGB,RF Components,Multivariate RF
0,D.I. Yogyakarta,0.2750,0.2724,0.2745,0.2910,0.2969
1,Jawa Tengah,0.3128,0.3125,0.3113,0.3343,0.3386

In [42]:
from openpyxl import load_workbook

file_evaluasi = OUTPUT_PATH / "tabel_evaluasi_model_2025.xlsx"

with pd.ExcelWriter(
    file_evaluasi,
    engine="openpyxl"
) as writer:

    # =========================
    # RMSE
    # =========================
    tabel_rmse.round(4).to_excel(
        writer,
        sheet_name="RMSE_per_kabupaten",
        index=False
    )

    ringkasan_rmse.round(4).to_excel(
        writer,
        sheet_name="RMSE_rata2_prov",
        index=False
    )

    # =========================
    # KENDALL TAU-B
    # =========================
    tabel_tau.round(4).to_excel(
        writer,
        sheet_name="Tau_per_kabupaten",
        index=False
    )

    ringkasan_tau.round(4).to_excel(
        writer,
        sheet_name="Tau_rata2_prov",
        index=False
    )

    # =========================
    # IE40
    # Simpan dalam bentuk proporsi 0-1
    # =========================
    tabel_ie40.to_excel(
        writer,
        sheet_name="IE40_per_kabupaten",
        index=False
    )

    ringkasan_ie40.to_excel(
        writer,
        sheet_name="IE40_rata2_prov",
        index=False
    )


# ==================================================
# FORMAT IE40 MENJADI PERSEN DI EXCEL
# ==================================================

wb = load_workbook(file_evaluasi)

# -------------------------
# IE40 per kabupaten
# -------------------------
ws = wb["IE40_per_kabupaten"]

# Kolom C-G = 5 model
for row in ws.iter_rows(
    min_row=2,
    min_col=3,
    max_col=7
):
    for cell in row:
        cell.number_format = "0.00%"

# -------------------------
# IE40 rata-rata provinsi
# -------------------------
ws = wb["IE40_rata2_prov"]

# Kolom B-F = 5 model
for row in ws.iter_rows(
    min_row=2,
    min_col=2,
    max_col=6
):
    for cell in row:
        cell.number_format = "0.00%"

wb.save(file_evaluasi)

print("Tersimpan:", file_evaluasi)

Tersimpan: d:\.STIS 64\SKRIPSI\Skripsi\PMT\output\tabel_evaluasi_model_2025.xlsx